spring:
  datasource:
    # Для локального запуска используйте localhost:
    # url: jdbc:postgresql://localhost:5432/users
    # username: postgres
    # password: postgres
    # Для Docker Compose используйте db:
    url: jdbc:postgresql://db:5432/users
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret-file: ${JWT_SECRET_PATH}
  expiration: 3600
server:
  port: 8080 