secrets:
  jwt_secret:
    file: ./secrets/jwt_secret.key

services:
  userdb:
    image: postgres:16-alpine
    container_name: user-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d users"]
      interval: 10s
      retries: 5

  user-service:
    build: .
    container_name: user-service
    restart: on-failure
    depends_on:
      userdb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:5432/users
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    ports:
      - "8081:8080"
    secrets:
      - jwt_secret

volumes:
  user_data: